# Generated by Django 4.2.17 on 2024-12-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('is_available', models.BooleanField(verbose_name='Доступность книги')),
                ('user', models.EmailField(max_length=254, verbose_name='Почта пользователя')),
            ],
        ),
    ]
