# Generated by Django 4.2.17 on 2024-12-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='user',
            field=models.EmailField(default=None, max_length=254, verbose_name='Почта пользователя'),
        ),
    ]
